"use strict";

module.exports = {
  CHANGE_BPM: "CHANGE_BPM",
  CHANGE_TRACK: "CHANGE_TRACK",
  CLEAR: "CLEAR",
  RANDOM: "RANDOM",
  TICK_SEQUENCER: "TICK_SEQUENCER",
  TOGGLE_MATRIX: "TOGGLE_MATRIX",
  TOGGLE_PLAY: "TOGGLE_PLAY",
  UPDATE_STATE: "UPDATE_STATE",
};
